Traceback (most recent call last):
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eddifying/micromamba/envs/seaocn_env/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot the fields
ncfile = ncnames_L1[0]
ncfile = 'data/a1_20160713_20170513_0480m_L1.adcp.nc'
dest_fig = 'figures/'
output_files = plot_westcoast_nc_LX.create_westcoast_plots(
    ncfile, dest_fig, "RegOz", do_all_plots=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[5], line 5[0m
[1;32m      3[0m ncfile [38;5;241m=[39m [38;5;124m'[39m[38;5;124mdata/a1_20160713_20170513_0480m_L1.adcp.nc[39m[38;5;124m'[39m
[1;32m      4[0m dest_fig [38;5;241m=[39m [38;5;124m'[39m[38;5;124mfigures/[39m[38;5;124m'[39m
[0;32m----> 5[0m output_files [38;5;241m=[39m [43mplot_westcoast_nc_LX[49m[38;5;241;43m.[39;49m[43mcreate_westcoast_plots[49m[43m([49m
[1;32m      6[0m [43m    [49m[43mncfile[49m[43m,[49m[43m [49m[43mdest_fig[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mRegOz[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdo_all_plots[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m~/micromamba/envs/seaocn_env/lib/python3.8/site-packages/pycurrents_ADCP_processing-1.0.1-py3.8.egg/pycurrents_ADCP_processing/plot_westcoast_nc_LX.py:2593[0m, in [0;36mcreate_westcoast_plots[0;34m(ncfile, dest_dir, filter_type, along_angle, time_range, bin_range, single_bin_inds, single_bin_depths, colourmap_lim, override_resample, do_all_plots, do_diagnostic, do_pressure, do_single_bin_ne, do_ne, do_ac, do_quiver, do_single_rotary_spectra, do_tidal, do_profile_rotary_spectra, do_filter_ne, do_filter_ac)[0m
[1;32m   2589[0m     [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mfilter_type value not understood ![39m[38;5;124m"[39m)
[1;32m   2591[0m [38;5;66;03m# Limit data[39;00m
[1;32m   2592[0m time_lim, bin_depths_lim, ns_filt_lim, ew_filt_lim, time_range_idx, bin_range_idx [38;5;241m=[39m limit_data(
[0;32m-> 2593[0m     ncdata, [43mew_filt[49m, ns_filt, time_range, bin_range)
[1;32m   2595[0m [38;5;66;03m# Northward and eastward velocity colormesh plots[39;00m
[1;32m   2596[0m [38;5;28;01mif[39;00m do_filter_ne [38;5;129;01mor[39;00m do_all_plots:

[0;31mUnboundLocalError[0m: local variable 'ew_filt' referenced before assignment

